config/routes.rb
Rails.application.routes.draw do
  # resources :photos for future implementation of photo uploads


  resources :lessons do
    resources :contributions, only: [:create]
  end
  
  resources :contributions, only: [:edit, :update, :destroy]
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}

  resources :users, only: :show

  root to:"application#home"

end

app/models/user.rb
class User < ApplicationRecord
  has_many :contributions
  has_many :lessons, through: :contributions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  validates :username, presence: true, uniqueness: true

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.nickname
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!

   def show
      @user = current_user
      @contributions = @user.contributions.reverse
   end
end

app/views/users/show.html.erb
<h1><%= @user.username %></h1>

<%= link_to "Edit Account", edit_user_registration_path, class: "pure-button button-warning" %>

<h3>My Contributions</h3>

<% @contributions.each do |c| %>
   <section class="post">
      <h2 class="content-subhead">From Lesson: <%= link_to c.lesson.name, lesson_path(c.lesson) %></h2>
            <div class="post-description trix-content"><%= sanitize c.content %></div>
      <p><%= update_buttons(c) %></p>
   </section>
<% end %>