config/routes.rb
Rails.application.routes.draw do
  # resources :photos for future implementation of photo uploads


  resources :lessons do
    resources :contributions, only: [:create]
  end
  
  resources :contributions, only: [:edit, :update, :destroy]
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}

  resources :users, only: :show

  root to:"application#home"

end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
   belongs_to :user
   belongs_to :lesson

   validates :content, presence: true

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
   before_action :authenticate_user!
   before_action :find_contribution, :check_contributor, only: [:edit, :update, :destroy]
   # before_action :check_contributor, only: [:edit, :update, :destroy]

   def create
      lesson = Lesson.find_by(id: params[:lesson_id])
      @contribution = Contribution.new(user: current_user, lesson: lesson, content: contribution_params[:content])
      if @contribution.save
         redirect_to lesson_path(lesson)
      else
         redirect_to lesson_path(lesson), alert: "Content was empty."
      end
   end

   def edit
   end

   def update
      if @contribution.update(contribution_params)
         redirect_to lesson_path(@contribution.lesson)
      else
         render :edit
      end
   end

   def destroy
      @lesson = @contribution.lesson
      @contribution.destroy
      redirect_to lesson_path(@lesson), notice: "Contribution deleted"
   end

   private
      def contribution_params
         params.require(:contribution).permit(:content)
      end

      def find_contribution
         @contribution = Contribution.find_by(id: params[:id])
      end

      def check_contributor
         if @contribution.user != current_user
            redirect_to lesson_path(@contribution.lesson), alert: "You are not permitted to modify that contribution."
         end
      end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
   
end

app/views/contributions/_form.html.erb
 <% if user_signed_in? %>
   <em><strong>Note from developer:</strong> Images uploaded will not persist because I'm too broke to afford a proper hosting service. For now, please upload your images to a site like <a href="https://imgur.com/upload" alt="Imgur Upload Link">Imgur</a> and paste the URL here. I will consider a hosting service once I have cash-money-all-day and more knowledge on how to implement such features. Thank you for reading!</em>
  <br><br>
  <%= form_for contribution, url: url do |f| %> 
    <%= f.trix_editor :content, required: true, autofocus: true, rows:"50", cols: "100" %>
    <br>
    <%= f.submit class: "pure-button button-success" %>
  <% end %>

<% else %>
    <h4 style="color:red">Please Sign In to contribute.</h4>
<% end %>

<hr>

app/views/contributions/edit.html.erb
<h1>Edit Contribution</h1>

<%= render partial: 'form', locals: {contribution: @contribution, url: contribution_path(@contribution)} %>
<br>
<%= link_to "Delete Contribution", contribution_path(@contribution), method: :delete %>