config/routes.rb
Rails.application.routes.draw do
  # resources :photos for future implementation of photo uploads


  resources :lessons do
    resources :contributions, only: [:create]
  end
  
  resources :contributions, only: [:edit, :update, :destroy]
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}

  resources :users, only: :show

  root to:"application#home"

end

app/models/lesson.rb
class Lesson < ApplicationRecord
   has_many :contributions
   has_many :users, through: :contributions

   validates_presence_of :name, :creator_id

   def clean_name
      name.gsub("-", " ")
   end

   def creator_is?(user)
      !!(self.creator_id == user.id) unless user.nil?
   end 
end
 

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
   include LessonsHelper
   before_action :find_lesson, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!, except: [:index, :show]
   before_action :check_creator, only: [:edit, :update, :destroy]

   def new
      @lesson = Lesson.new
   end

   def create
      @lesson = Lesson.new(lesson_params) do |user|
         user.creator_id = current_user.id
      end

      if @lesson.save
         redirect_to lesson_path(@lesson), notice: "Lesson created!"
      else
         render :new
      end
   end

   def index
      @lessons = Lesson.all.reverse
   end

   def show
      if @lesson.nil?
         redirect_to lessons_path, alert: "Lesson not found."
      end
      @contribution = Contribution.new
   end

   def edit

   end

   def update
      if @lesson.update(lesson_params)
         redirect_to lesson_path(@lesson)
      else
         render :edit
      end
   end

   def destroy
      contributions = Contribution.where(lesson_id: @lesson.id)
      contributions.destroy_all
      @lesson.destroy
      redirect_to lessons_path, notice: "Lesson deleted"
   end

   private 
      def find_lesson
         @lesson = Lesson.find_by(id: params[:id])
      end

      def lesson_params
         params.require(:lesson).permit(:name, :category, :section)
      end

      def check_creator
         if @lesson.creator_is?(current_user)
            return
         else
            redirect_to lessons_path, alert: "You are not permitted to modify this #{@lesson.name}."
         end
      end
end

app/helpers/lessons_helper.rb
module LessonsHelper  
   def display_user(content)
      if !!content.user
         content.user.username
      else
         "Unknown Source"
      end
   end
end

app/views/lessons/_form.html.erb
<%= form_for lesson, html: {class:"pure-form"} do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %> <br><br>
   <span class="pure-form-message-inline">Be as accurate as possible with the name.</span> 
   <br>
   <br>
   
   <%= f.label :category %>
   <%= f.text_field :category %> <br><br>

   <%= f.label :section %>
   <%= f.text_field :section %> <br><br>

   <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit the Lesson</h1>


<%= render partial:'form', locals: {lesson: @lesson} %>

<%= button_to "Delete Lesson", lesson_path(@lesson), method: :delete %>

app/views/lessons/index.html.erb
<h1>All Lessons</h1>
<% if user_signed_in?  %>
   <%= link_to "Add a lesson", new_lesson_path, class: "pure-button button-success" %>
<% end %>

<br><br>

<script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i, txtValue;
  input = document.getElementById('myInput');
  filter = input.value.toUpperCase();
  ul = document.getElementById("myUL");
  li = ul.getElementsByTagName('li');

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    txtValue = a.textContent || a.innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>

<input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for Lesson">

<ul id="myUL">
<% @lessons.each do |l| %>
   <li><%= link_to l.clean_name, lesson_path(l) %></li>
<% end %>
</ul>

app/views/lessons/new.html.erb
<h1>Create New Lesson</h1>

<%= render partial:'form', locals: {lesson: @lesson} %>

app/views/lessons/show.html.erb
<h1 class="post-title">Lesson: <%= @lesson.clean_name %></h1>


<%= link_to "Edit this Lesson", edit_lesson_path(@lesson), class: "pure-button button-warning" if @lesson.creator_is?(current_user) %>



<h4 class="content-subhead">Add Hints and Tips For This Lesson</h4>
<section class="post">
   <%= render partial: 'contributions/form', locals: {contribution: @contribution, url: lesson_contributions_path(@lesson)} %>
</section>


<br><br>

<h2 class="content-subhead">Comments:</h2>
<% @lesson.contributions.each do |c| %>
   <section class="post">
      <header class="post-header">
         <h2 class="post-title">From <%= display_user(c)%><h2>
      </header>
      <div class="post-description trix-content"><%= sanitize c.content %></div>
      <p><%= update_buttons(c) %></p>
   </section>
<% end %> 