config/routes.rb
Rails.application.routes.draw do
  # resources :photos for future implementation of photo uploads


  resources :lessons do
    resources :contributions, only: [:create]
  end
  
  resources :contributions, only: [:edit, :update, :destroy]
  devise_for :users, controllers: {registrations: "registrations", omniauth_callbacks: "callbacks"}

  resources :users, only: :show

  root to:"application#home"

end

app/views/layouts/_flash.html.erb
<% if notice %>
   <p class="alert alert-success" style="color:green"><%= notice %></p>
<% end %>
<% if alert %>
   <p class="alert alert-danger" style="color:red"><%= alert %></p>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="nav">
   <ul class="nav-list">
      <li class="nav-item">
         <%= link_to "All Lessons", lessons_path, class: "pure-button" %>
      </li>
   </ul>
   <br><br>

   <% if user_signed_in? %>
   <ul class="nav-list">
      <li class="nav-item">
         <%= link_to '<i class="fas fa-user-circle"></i> My Account'.html_safe, user_path(current_user), class: "pure-button" %>
      </li>
   </ul>
   <% else %>
   <ul class="nav-list">
      <li class="nav-item">
         <%= link_to '<i class="fas fa-user-plus"></i> Sign Up'.html_safe, new_user_registration_path, class: "pure-button" %>
      </li>
   </ul>
   <% end %>

   <ul class="nav-list">
      <li class="nav-item">
         <%= auth_buttons %>
      </li>
   </ul>

   <br>

   <ul class="nav-list">
      <li class="nav-item">
         <a href="https://github.com/BebopVinh/learn-collective/issues" class="pure-button">Report Issues</a>
      </li>
   </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnCollective</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%# PureCSS %>
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
    <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">

    <%# Font-Awesome for Button-Icon %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'buttons', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" type="text/css" href="trix.css">
    <script type="text/javascript" src="trix.js"></script>
  </head>

  <body id="yui_3_18_1_1_1558162381059_11">
    <div class="pure-g" id="layout">
      <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
          <h1 class="brand-title">Learn-Collective</h1>
          <h2 class="brand-tagline">From Flatiron Students</h2>

        <%= render 'layouts/nav' %>

        </div>
        </div>

      <div class="content pure-u-1 pure-u-md-3-4">
        <%= render 'layouts/flash' %>
        <%= yield %>
      </div>  
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <meta http-equiv="X-UA-Compatible" content="ie=edge">
   <title>LearnCollective</title>

   <%# PureCSS %>
   <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/pure-min.css" integrity="sha384-nn4HPE8lTHyVtfCBi5yW9d20FjT8BJwUXyWZT9InLYax14RDjBj46LmSztkmNP9w" crossorigin="anonymous">
   <link rel="stylesheet" href="https://unpkg.com/purecss@1.0.0/build/grids-responsive-min.css">

   <%# Font-Awesome for Button-Icon %>
   <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">



   <%= stylesheet_link_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
   <%= stylesheet_link_tag 'buttons', media: 'all', 'data-turbolinks-track': 'reload' %>

</head>
<body>
   <video playsinline autoplay muted loop id="bgvid">
      <source src="code_landing.mp4" type="video/mp4">
   </video>

   <header class="viewport-header">
   <h1>Learn Collective
   <br>
   <span>
   <h3>From Flatiron Students</h3>
   </span>
   </h1>
   </header>

   <%= render 'layouts/flash' %>
   
   <main>
      <%= yield %>
   </main>

</body>
</html>